CREATE DATABASE Shop;
CREATE TABLE Info (
	ID SERIAL PRIMARY KEY,
	FirstName VARCHAR(50) NOT NULL,
	LastName VARCHAR(50) NOT NULL,
	Gender VARCHAR(6),
	Country VARCHAR(50),
	Age SMALLINT,
	Date DATE
);
